// <Autogenerated>
#include <stdio.h>

typedef unsigned char byte;

byte tape[30000] = {0};

int main(void)
{
    int index = 0;
    // START
        tape[index] += 10;
    while(tape[index]) {
        index++;
        tape[index] += 7;
        index++;
        tape[index] += 10;
        index++;
        tape[index] += 3;
        index++;
        tape[index]++;
        index -= 4;
        tape[index]--;
    }
    index++;
    tape[index] += 2;
    putchar(tape[index]);
    index++;
    tape[index]++;
    putchar(tape[index]);
    tape[index] += 7;
    putchar(tape[index]);
    putchar(tape[index]);
    tape[index] += 3;
    putchar(tape[index]);
    index++;
    tape[index] += 2;
    putchar(tape[index]);
    index -= 2;
    tape[index] += 15;
    putchar(tape[index]);
    index++;
    putchar(tape[index]);
    tape[index] += 3;
    putchar(tape[index]);
    tape[index] -= 6;
    putchar(tape[index]);
    tape[index] -= 8;
    putchar(tape[index]);
    index++;
    tape[index]++;
    putchar(tape[index]);
    index++;
    putchar(tape[index]);
    // END
    return 0;
}